spring:
  application:
    name: full-stack-guide
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres_dev
    username: dev
    password: password